<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ftl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|nav|section|aside|header|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		|(\[|&lt;)(\#|@)\w+.*\(\]|&gt;)
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|nav|section|aside|header|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		|(\[|&lt;)/(\#|@)\w+.*(\]|&gt;)
		)</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>FreeMarker</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>[&lt;\[]#--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ftl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--[&gt;\]]</string>
			<key>name</key>
			<string>comment.block.ftl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.ftl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.ftl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ftl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.ftl</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ftl</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.ftl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([&lt;\[](#|@))(\w+(\.\w+)*)((\s+[^&gt;\]]+)*?)\s*((\/)?([&gt;\]]))</string>
			<key>name</key>
			<string>meta.function.ftl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.ftl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.ftl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ftl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.ftl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([&lt;\[]\/(#|@))(\w+(\.\w+)*)\s*([&gt;\]])</string>
			<key>name</key>
			<string>meta.function.ftl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.ftl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ftl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.ftl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$\{)\.?[a-zA-Z_\(][\w\(\)+-\/\*]+(\.?[\w\(\)+-\/\*]+)*(.*?|\?\?|\!)?(\})</string>
			<key>name</key>
			<string>variable.other.readwrite.local.ftl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ftl</string>
	<key>uuid</key>
	<string>C011BB07-875D-4DEB-9582-0E1FEC0D1E4E</string>
</dict>
</plist>
